config/routes.rb
BobbyStore::Application.routes.draw do
  
  devise_for :users
  
  devise_scope :user do
    get '/' => "home#index" 
  end

  resources :clients, only: [:new, :create, :index, :edit, :update]
  get 'clients/:client_id/terms' => 'clients#terms', as: 'terms_conditions'
  get 'clients/:client_id/terms_approval' => 'clients#terms_approval', as: 'terms_approval'
  delete 'clients/:client_id/delete_client' => 'clients#delete_client', as: 'delete_client'

  resources :item_groups, only: [:new, :create, :index]

  resources :depot_notices, only: [:create, :index]

  resources :items, only: [:show, :update]
  post 'items/:item_id/sell' => 'items#sell', as: 'sell_item'
  post 'items/:item_id/unsell' => 'items#unsell', as: 'unsell_item'
  post 'items/:item_id/mark_as_paid' => 'items#mark_as_paid', as: 'mark_item_payment'

  delete 'items/:item_id/delete_item' => 'items#delete_item', as: 'delete_item'
  
  get 'item_groups/add_item' => 'item_groups#add_item', as: 'add_item'
  post 'item_groups/:id/delete_item_group' => 'item_groups#delete_item_group', as: 'delete_item_group'
  get 'clients/:client_id/item_groups/new' => 'item_groups#add_group_only', as: 'add_group_to_client'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  include PgSearch
  
  has_many :item_groups
  has_many :items
  has_one :user
  
  # pg_search_scope :search_customer, :against => [:first_name, :last_name]

  pg_search_scope :search_customer, associated_against: {
    items: [:reference] 
  }

  after_save :create_user_account

  scope :notified_depot_end, -> { where(notified_depot_end: true) }

  def full_name
  	self.first_name + ' ' + self.last_name
  end

  def create_user_account
  	User.create(:email => self.email, client_id: self.id)
  end

  def number_of_groups
    self.item_groups.count.to_s
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_group
  belongs_to :client

  def sell
  	self.update_attributes(sold: true, date_sold: Time.now)
  end

  def unsell
  	self.update_attributes(sold: false, date_sold: nil)
  end

  def sold_and_unpaid
  	self.sold? && !self.payment
  end

  def sold_and_paid
  	self.sold? && self.payment
  end

  def mark_as_paid(method)
  	self.update_attributes(payment: true, payment_type: method, payment_date: Time.now)
  end

end

app/models/item_group.rb
class ItemGroup < ActiveRecord::Base
  include PgSearch
  
  pg_search_scope :search_customer, :associated_against => {
    :client => [:first_name, :last_name],
  }

  has_many :items
  belongs_to :client
  accepts_nested_attributes_for :client
  accepts_nested_attributes_for :items


  def all_sold?
    return true if self.items.select {|item| item.sold != true }.blank?
    return false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :item_groups
  has_many :items
  belongs_to :client
  before_validation :set_generic_password

  def password_required?
    false
  end 

  def set_generic_password
  	self.password = 'password'
  end

  def admin?
    role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.sign_in_count == 1 && resource.client
      terms_conditions_path(resource.client.id)
    elsif resource.client
      request.env['omniauth.origin'] || stored_location_for(resource) || item_groups_path
    else
      clients_path
    end
  end
  
end

app/controllers/clients_controller.rb
require 'will_paginate'

class ClientsController < ApplicationController

  PER_PAGE = 2

  def index
    if params[:client_search].blank?
      @clients = current_user.admin? ? @clients = Client.all.paginate(page: params[:page], per_page: PER_PAGE,  order: "id DESC") : @clients = current_user.client
    else
      @search = params[:client_search]
      @clients = Client.search_customer(params[:client_search]).paginate(page: params[:page], per_page: PER_PAGE, order: "id DESC")
    end
    @clients = @clients
  end

  def new
  end

  def create
  end

  def edit
    @client = Client.find(params[:id])
  end
  
  def update
    client = Client.find(params[:id])
    client.update_attributes(client_params)
    redirect_to clients_path
  end

  def terms
  	@client = Client.find(params[:client_id])
  end

  def terms_approval
  	client = Client.find(params[:client_id])
  	approve_terms(client)
  	redirect_to item_groups_path
  end

  def delete_client
    client = Client.find(params[:client_id])
    client.item_groups.delete_all
    client.user.delete if client.user
    client.delete
    redirect_to clients_path
  end

  private

  def approve_terms(client)
  	client.update_attributes(agree_to_terms: true)
  end

  def client_params
    params[:client].permit(:last_name, :first_name, :email, :phone)
  end

end

app/controllers/depot_notices_controller.rb
class DepotNoticesController < ApplicationController
  
  def index
    # range = (Time.new(2013, 12, 05))..Time.now.midnight - 2.months
    range = (Time.now.midnight - 2.months)..Time.now
    @clients = Client.where(created_at: range).where(notified_depot_end: nil)
  end

  def create
    client = Client.find(params[:client_id])
    ClientNotifier.end_of_depot(client).deliver!
    client.update_attributes(notified_depot_end: true)
    redirect_to :back
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@no_nav = true
  	@color_container = true
  	@image_background = true
  end

end

app/controllers/item_groups_controller.rb
class ItemGroupsController < ApplicationController
  before_filter :authenticate_user!
    
  def index    
    if params[:client_search].blank?
      @item_groups = current_user.admin? ? @item_groups = ItemGroup.all : @item_groups = current_user.client.item_groups
    else
      @item_groups = ItemGroup.search_customer(params[:client_search])
    end
  end

  def new
  	@item_group = ItemGroup.new
  	@item_group.build_client
  	
  	respond_to do |format|
  	  format.html
  	  format.xml { render xml: @item_group }
  	end
  end

  def add_group_only
    @client = Client.find(params[:client_id])
    @item_group = ItemGroup.new
  end

  def create
    if params[:item_group][:client_id]
      @client = Client.find(params[:item_group][:client_id]) 
    else
      @client = Client.create(client_params)
    end
  	@item_group = @client.item_groups.create(item_group_params)  	
    params[:item_group][:items].each do |k, v|
      @item_group.items.create(item_params(k).merge(client_id: @client.id))
    end
    redirect_to clients_path
  end

  def add_item
    respond_to do |format|
      format.js { 'add_item.js.erb' }
    end
  end

  def delete_item_group
    item = ItemGroup.find(params[:id])
    item.delete
    redirect_to :back
  end

  private

  def client_params
  	params[:item_group][:client_attributes].permit(:first_name, :last_name, :email, :phone)
  end
  
  def item_group_params
  	params[:item_group][:item_group].permit(:begin_date, :end_date)
  end

  def item_params(key)
    params[:item_group][:items][key].permit(:brand, :product, :reference, :buy_price, :sell_price)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
    
  def show
    @item = Item.find(params[:id])
    @search = params[:client_search] if params[:client_search]
    respond_to do |format| 
      format.js 
    end
  end

  def update
    item = Item.find(params[:id])
    item.update_attributes(item_params)
    redirect_to clients_path(client_search: params[:item][:client_search])
  end

  def delete_item
    item = Item.find(params[:item_id])
    item.delete
    redirect_to :back
  end

  def sell
    item = Item.find(params[:item_id])
    item.sell
    if item.item_group.all_sold?
      notify_client_end_of_depot(item.client)
    end
    redirect_to :back
  end

  def unsell
    item = Item.find(params[:item_id])
    item.unsell
    redirect_to :back
  end

  def mark_as_paid
    item = Item.find(params[:item_id])
    item.mark_as_paid(params[:payment_method])
    redirect_to :back
  end

  private

  def item_params
    params[:item].permit(:sell_price, :date_sold, :payment, :payment_type)
  end

  def notify_client_end_of_depot(client)
    ClientNotifier.end_of_depot(client).deliver!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.haml
%h1 Update Client
= form_for @client do |f|
  = f.label :last_name, 'Nom'
  = f.text_field :last_name
  = f.label :first_name, 'Prénom'
  = f.text_field :first_name
  = f.label :email
  = f.text_field :email
  = f.label :phone
  = f.text_field :phone
  %br
  = f.submit :class => "btn btn-large btn-success", value: "Save"

app/views/clients/index.html.haml
.header
  .row-fluid
    .span6
      %h1 Bobby SecondHand
    .span6
      - if current_user.admin?
        = form_tag clients_path, class: 'pull-right pull-down', method: :get do
          = text_field_tag :client_search, params[:search], data: { keybinding: '/' }
          = submit_tag "Chercher", class: "btn btn-primary client-search"

.distance-top-30
  - if @clients
    - @clients.each_with_index do |client, index|
      - client.item_groups.each_with_index do |group, i|
        .row-fluid
          .span3
            - if i == 0
              %h4
                = client.full_name
                %span.badge
                  = client.number_of_groups
              = client.email
              %br
              = client.phone
              %br
              
          .span7

          .span2.pull-right
            - if i < 1
              %h4 Menu
              = link_to 'Modification Client', edit_client_path(id: group.client.id)
              %br
              = link_to 'Ajoute un Dépôt', add_group_to_client_path(client_id: group.client.id)
              %br
              = link_to 'Supprimer Client', delete_client_path(client_id: client.id), method: :delete
            
        %hr

          %table.table.table-striped
            %thead
              %tr
                %td
                  %h3
                    = i +1

                %td
                  %h6 Date de dépôt
                  = group.begin_date.strftime('%d-%m-%Y')
                %td
                  %h6 Date fin de dépôt
                  = group.end_date.strftime('%d-%m-%Y')
                %td
                %td
                %td
                %td
                  = link_to 'Supprimer dépôt', delete_item_group_path(id: group.id), method: :post
              %tr
                %th Marque
                %th Produit
                %th Reference
                %th Prix d'achat
                %th Prix de vente
                %th Action
                %th Supprimer
            - group.items.each do |item|  
              - if !item.sold?
                - next_state_change = link_to 'vendu', sell_item_path(item_id: item.id, client_search: @search), method: :post
              - elsif item.sold_and_unpaid
                - next_state_change = (link_to 'check', mark_item_payment_path(item_id: item.id, client_search: @search, payment_method: 'check'), method: :post) + ' ' + (link_to 'cash', mark_item_payment_path(item_id: item.id, client_search: @search, payment_method: 'cash'), method: :post)
              - if item.sold?
                - highlight_color = item.sold_and_paid ? 'highlight-purple' : 'highlight-green'
              %tr{class: (highlight_color)}
                %td
                  = item.brand
                %td
                  = item.product
                %td
                  = item.reference
                %td
                  = item.buy_price
                %td
                  = item.sell_price
                %td
                  = next_state_change
                %td
                  = link_to 'X', delete_item_path(item_id: item.id), method: :delete
                -if item.sold_and_paid
                  %td
                    - if item.payment_type == 'check'
                      = 'cheque le '
                      = item.payment_date.strftime('%d-%m-%Y') if item.payment_date
                    - else 
                      = 'espece le'
                      = item.payment_date.strftime('%d-%m-%Y') if item.payment_date
                  / = link_to '', item_path(id: item.id, client_search: @search ), data: {toggle: 'modal', target: "#showModal"}, 'data-keyboard' => true, remote: true, class: 'delete-pay-fail icon-book icon-2x no-decoration'
        - if @clients.length > (index + 1)
          %hr.black

= will_paginate @clients, renderer: BootstrapPagination::Rails if @clients

app/views/clients/terms.html.haml
%h1 TERMS AND CONDITIONS

%br
%br
%h4 Article 1
La marge du dépôt-vente est de 50% du prix de vente par article.

%br
%br
%h4 Article 2
Passé 3 semaines de mise en vente, Bobby se réserve le droit de retirer certains articles de la vente si ils ne correspondent pas à la demande.

%br
%br
%h4 Article 3
Les articles sont en vente pendant 2 mois (congés de moins d'un moins incluent). Les déposants ont une semaine pour venir récupérer les invendus. Passé ce délai, si le déposant n’est pas venu récupérer ses produits, Bobby pourra considérer qu’il fait abandon de ceux-ci, et en conséquence, que le déposant renonce à toute possibilité de réclamation en restitution.

%br 
%br
%h4 Article 4
Le Déposant s’interdit pendant une durée de deux mois, à compter de la signature du présent Contrat, d’intervenir dans la vente des biens confiés a Bobby, et ceci, de quelque façon que ce soit, et notamment de retirer tout ou partie desdits biens au Dépositaire, sauf à verser, à titre de dédommagement, le montant de la commission initiale prévue.

%br
%br
%br
%br
%h3
  = link_to "Je suis d'accord", terms_approval_path(client_id: @client.id)

app/views/depot_notices/index.html.haml
%br
%h1.center Clients qui ont besoin de venir chercher leur dépôt
%br
%br
%table.table.table-striped
  - @clients.each do |client|
    %tr
      %td
        = client.first_name
        = client.last_name
      %td	
        = link_to 'envoyer notice', depot_notices_path(client_id: client.id), method: :post

app/views/home/index.html.haml
%hr/
= image_tag 'bobby_logo.jpg', width: '900'
/ = "Bobby DEPOT-VENTE"

%hr/
%ul.nav.nav-pills.pull-right
  %li.pull-right
    
.container-narrow
  / .jumbotron
  /   %h1 Super awesome marketing speak!
  /   %p.lead Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
  / %a.btn.btn-large.btn-success{href: "#"} Sign up today
  
  .row-fluid.marketing.distance-top-30
    .span4
      %h4 Contact
      %p 
        = "Bobby Dépôt-Vente Femme"
        %br
        = "9 rue Oberkampf"
        %br
        =  "75011"
        %br
        = "01 72 38 54 83"
        %br
        = "bobbysecondhand@gmail.com"
      #map-canvas
      %hr
      %p
        =  "Mardi-Samedi 11h - 20h"
        %br
        =  "Métro: Filles du Calvaire, Oberkampf, République"
        %br

    
    .span6.offset2
      .right-panel
        %h4 WANTED
        %p
          = "* Type de vétements/chaussures/accessoires recherché:"
          %p.indent-30
            = "*récent, à la mode "
          %p.indent-70
            = "OU"
          %p.indent-30
            = "*grand classique"
          %p
            =  "* Les vêtements doivent être lavés, repassés et de saison."
        %h4 Conditions
        %p 
          = "* 50 % pour vous / 50% pour Bobby"
          %br
          = "* La durée des dépôts est de deux mois."
          %h4 Pour déposer:
          %p 
            = "* Dépôts sans rendez-vous du mardi au samedi de 11 h à 20h (éviter l'heure du déjeuner)."
        
      
  %hr/
  .footer
    %p © Bobby 2014
/ /container

app/views/item_groups/_item_fields.html.erb
<% rand_number = rand(999) %>
<fieldset class='item-form'>
  <div class="row-fluid">
    <div class="span2">
      <label for="item_group_item_brand">Marque</label>
      <input class="input-small" id="item_group_item_brand" name="item_group[items][item_<%= rand_number %>][brand]" type="text" >
    </div>
    <div class="span2">
      <label for="item_group_item_product">Produit</label>
      <input class="input-small" id="item_group_item_product" name="item_group[items][item_<%= rand_number %>][product]" type="text">
    </div>
    <div class="span2">
      <label for="item_group_item_reference">Référence</label>
      <input class="input-small reference" id="item_group_item_reference" name="item_group[items][item_<%= rand_number %>][reference]" type="text">
    </div>
    <div class="span2">
      <label for="item_group_item_buy">Prix de vente</label>
      <input class="input-small" id="item_group_item_sell_price" data=<%= rand_number %> name="item_group[items][item_<%= rand_number %>][sell_price]" type="text">
    </div>
    <div class="span2">
      <label for="item_group_item_buy">Prix d'achat</label>
      <input class="input-small" id="item_group_item_buy_price" data=<%= rand_number %> name="item_group[items][item_<%= rand_number %>][buy_price]" type="text">
    </div>
  </div>
</fieldset>

app/views/item_groups/add_group_only.html.haml
= form_for @item_group do |f|
  = f.hidden_field :client_id, value: @client.id
  = f.fields_for :item_group do |item_group|
    .row-fluid
      .span6
        = item_group.label :begin_date, 'Date dépôt'
        = item_group.text_field :begin_date, class: 'datepicker', value: Time.now.strftime('%d-%m-%Y')
      .span6
        = item_group.label :end_date, 'Date fin de dépôt'
        = item_group.text_field :end_date, class: 'datepicker', value: (Time.now + 60.days).strftime('%d-%m-%Y')
    %h3 Products
    = link_to add_item_path, remote: :true, f: f, class: 'pull-right' do
      %icon.icon-plus-sign.icon-2x.add-item.no-decoration
    = f.fields_for :item do |item|
      / .row-fluid
      /   .span2
      /     = item.label :brand
      /     = item.text_field :brand, class: 'input-small'
      /   .span2
      /     = item.label :product
      /     = item.text_field :product, class: 'input-small'
      /   .span2
      /     = item.label 'reference'
      /     = item.text_field :reference, class: 'input-small'
      /   .span2
      /     = item.label 'buy'
      /     = item.text_field :buy_price, class: 'input-small'
      = render 'item_groups/item_fields' 
  = f.submit :class => "btn btn-large btn-success", value: "Save"

app/views/item_groups/add_item.js.erb
var oldVal = $('.reference').last().val();

$('.item-form')
  .last()
  .append("<%= escape_javascript("#{render :partial => 'item_fields'}").html_safe %>");

var numbers = [];
var letters = [];

if (typeof oldVal != "undefined") {
  for (var i = 0; i < oldVal.length; i++) {
    if (oldVal.charAt(i) >= 0 && oldVal.charAt(i) <= 9) {
      numbers.push(oldVal.charAt(i));
    } else {
      letters.push(oldVal.charAt(i));
    }
  }
}

var newVal = (parseInt(numbers.join("")) + 1).toString();
var newFieldText = letters.join("") + newVal; 

if (newFieldText == "NaN") {
  var newFieldText = ""
}

$('.reference').last().val(newFieldText)

app/views/item_groups/index.html.haml
.header
  .row-fluid
    .span6
      %h1 Bobby SecondHand
    .span6
      - if current_user.admin?
        = form_tag item_groups_path, class: 'pull-right pull-down', method: :get do
          = text_field_tag :client_search, params[:search], data: { keybinding: '/' }
          = submit_tag "Search", class: "btn btn-primary client-search"

.distance-top-30
  - @item_groups.each_with_index do |group, index|
    .row-fluid
      .span4
        - if index == 0
          %h4
            = group.client.full_name

            %span.badge
              = group.client.number_of_groups
          = group.client.email
          %br
          = group.client.phone
      .span3
        %h6 Date de dépôt
        = group.begin_date
      .span3
        %h6 Date fin de dépôt
        = group.end_date
      .span2
    %hr
    %table.table.table-striped
      %thead
        %tr
          %th Brand
          %th Product
          %th Reference
          %th Buy price
          %th Sell price
          %th Payment
      - group.items.each do |item|  
        %tr{class: ('highlight-green' if item.sold?)}
          %td
            = item.brand
          %td  
            = item.product
          %td  
            = item.reference
          %td  
            = item.buy_price
          %td  
            = item.sell_price
          %td
            = item.payment
          - if current_user.admin?  
            %td
              = link_to '', item_path(id: item.id), data: {toggle: 'modal', target: "#showModal"}, 'data-keyboard' => true, remote: true, class: 'delete-pay-fail icon-book icon-2x no-decoration'
    - if @item_groups.length > (index + 1)
      %hr.black

app/views/item_groups/new.html.haml
= form_for [@client, @item_group], url: item_groups_path, method: :post do |f|
  %h3 Customer Info
  = f.fields_for :client do |client|
    .row-fluid
      .span6
        = client.label :last_name, 'Nom'
        = client.text_field :last_name
      .span6
        = client.label :first_name, 'Prénom'
        = client.text_field :first_name
    .row-fluid
      .span6
        = client.label :email
        = client.text_field :email
      .span6
        = client.label :phone
        = client.text_field :phone
  = f.fields_for :item_group do |item_group|
    .row-fluid
      .span6
        = item_group.label :begin_date, 'Date dépôt'
        = item_group.text_field :begin_date, class: 'datepicker', value: Time.now.strftime('%d-%m-%Y')
      .span6
        = item_group.label :end_date, 'Date fin de dépôt'
        = item_group.text_field :end_date, class: 'datepicker', value: (Time.now + 2.months).strftime('%d-%m-%Y')
  %h3 Products
  = link_to add_item_path, remote: :true, f: f, class: 'pull-right' do
    %icon.icon-plus-sign.icon-2x.add-item.no-decoration
  = f.fields_for :item do |item|
    = render 'item_groups/item_fields'     
  = f.submit :class => "btn btn-large btn-success", value: "Save"

app/views/items/_content.html.haml
#showModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "showModalLabel", role: "dialog", tabindex: "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
    %h3#showModalLabel
      = item.product + ' ' + 'de' + ' ' + item.client.full_name
  .modal-body
    .row-fluid
      .span3
        %h4 Marque
        = item.brand
      .span3  
        %h4 Produit
        = item.product
      .span3  
        %h4 Reference
        = item.reference
      .span3
        %h4 Prix d'achat
        = item.buy_price
    %hr
    %h3 Changer status
    = form_for @item do |f|
      = f.hidden_field :client_search, value: search
      .row-fluid
        .span4
          %h4 Sell price
          = f.text_field :sell_price, class: 'input-small'
        .span4
          %h4 Date sold
          = f.text_field :date_sold, class: 'datepicker input-small'
        .span4
          %h4 Payment
          .row-fluid
            .span6
              = 'true'
              %br
              = f.radio_button :payment, true
            .span6
              = 'false'
              %br
              = f.radio_button :payment, false
      %br
      %button.btn.btn-large{"aria-hidden" => "true", "data-dismiss" => "modal"} Close    
      = f.submit class: "btn btn-large btn-success", value: "Save"
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BobbyStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Neuton' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyA9JAHlzo-tYMtwhlttLEW_qqOwmg0rPXY&sensor=true" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
</head>
<body class=<%= 'image_background' if @image_background %>>
  <%= render 'shared/nav' %>
  <div class=<%= 'color-container' if @color_container %>>
    <div class='wrapper'>
      <% unless flash['notice'].blank? %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% unless flash['alert'].blank? %>  
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/shared/_map.html.erb
<script>
  var initialize, toggleBounce;
  initialize = function() {
    var map, mapOptions, marker;
    mapOptions = {
      center: new google.maps.LatLng(48.863, 2.368189),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(48.863, 2.368189),
      map: map,
      animation: google.maps.Animation.DROP,
      title: "Hello World!"
    });
    return google.maps.event.addListener(marker, "click", toggleBounce);
  };

  toggleBounce = function() {
    if (marker.getAnimation() != null) {
      return marker.setAnimation(null);
    } else {
      return marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  };

  google.maps.event.addDomListener(window, "load", initialize);
</script>

app/views/shared/_nav.html.haml
- unless @no_nav == true
  .navbar
    .navbar-inner
      %a.brand{href: "/"} Bobby
      %ul.nav
        %li.active
        - if current_user && current_user.admin?
          %li 
            = link_to 'Clients', clients_path
          %li
            = link_to 'Nouveau Client', new_item_group_path
          %li
            = link_to "Dépot notices", depot_notices_path
        - if user_signed_in?
          %li
            = link_to 'Déconnexion', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Connexion', new_user_session_path